GET http://localhost:3001/api/persons
###

GET  http://localhost:3001/api/persons/923
###

DELETE http://localhost:3001/api/persons/2

###
PUT http://localhost:3001/api/persons/798
content-type: application/json

{
    "name": "test",
    "number": "123-456"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "test",
    "number": "11111"
}